//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int MedicineId { get; set; }
        public string MedicineName { get; set; }
        public int MedicineFormId { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int MedicineUnitId { get; set; }
        public int ManufacturerId { get; set; }
        public decimal Price { get; set; }
        public int PharmacyId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string InvoiceNumber { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MedicineForm MedicineForm { get; set; }
        public virtual MedicineUnit MedicineUnit { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
