//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Supplies = new HashSet<Supply>();
        }
    
        public int MedicineId { get; set; }
        public string MedicineName { get; set; }
        public int MedicineFormId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int MedicineUnitId { get; set; }
        public int ManufacturerId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MedicineForm MedicineForm { get; set; }
        public virtual MedicineUnit MedicineUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supplies { get; set; }
    }
}
