//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyId { get; set; }
        public int Quantity { get; set; }
        public int PharmacyId { get; set; }
        public int MedicineId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string InvoiceNumber { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
